# Generated by Django 4.1.7 on 2023-04-13 12:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("phone", models.CharField(max_length=50)),
                ("video", embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "Classified Ads",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                (
                    "category_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/category"
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Cities",},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Regions",},
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        default="default-profile-pic.png",
                        null=True,
                        upload_to="uploads/profile-pictures",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default=None, upload_to="uploads/%Y/%m/%d"),
                ),
                (
                    "ads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.ads"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Classified Ads Images",},
        ),
        migrations.AddField(
            model_name="ads",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ads.author"
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.category",
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ads.city"
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="region",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ads.region"
            ),
        ),
    ]
